#!/usr/bin/env python3
"""Bench-oriented varactor-loaded NLTL design for the 4->8->12 bridge.

This track moves from normalized transmission-line screening toward a concrete
low-RF nonlinear transmission line.  Discovery rows drive only the 50 MHz
source band.  Harmonics near 100 MHz and 150 MHz are generated by the
voltage-dependent capacitance of reverse-biased varactor diode models.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import shutil
import subprocess
from dataclasses import asdict, dataclass, replace
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np

import spice_412_export as spice_base


OUT_DIR = Path("runs") / "spice_412_varactor_nltl_design"
SOURCE_HZ = 50.0e6
GENERATED_HZ = 100.0e6
TARGET_HZ = 150.0e6
TOTAL_LENGTH_M = 0.38197186342054884
PHASE_VELOCITY_M_S = 5.0e6
TSTOP_S = 0.55e-6
TSTEP_S = 0.5e-9
TMAX_STEP_S = 0.2e-9
EPS = 1e-30
TL_BEHAVIORAL_BASELINE = 0.36


@dataclass(frozen=True)
class VaractorModel:
    cjo_f: float
    vj_v: float = 0.75
    m: float = 0.50
    rs_ohm: float = 0.85
    bv_v: float = 18.0
    ibv_a: float = 1.0e-6
    is_a: float = 1.0e-15


@dataclass(frozen=True)
class NLTLCase:
    case_id: str
    name: str
    filename: str
    role: str
    cell_count: int
    z0_ohm: float
    total_length_m: float = TOTAL_LENGTH_M
    phase_velocity_m_s: float = PHASE_VELOCITY_M_S
    source_amplitude_v: float = 2.0
    direct_generated_amplitude_v: float = 0.0
    bias_v: float = 4.0
    nonlinear_fraction: float = 0.82
    varactor_vj_v: float = 0.75
    varactor_m: float = 0.50
    varactor_rs_ohm: float = 0.85
    varactor_bv_v: float = 18.0
    varactor_ibv_a: float = 1.0e-6
    series_loss_ohm_scale: float = 1.0
    shunt_loss_ohm: float = 200_000.0
    target_phase_velocity_scale: float = 1.0
    generated_phase_velocity_scale: float = 1.0
    fixed_cap_only: bool = False
    band_shunts: bool = False
    source_only_drive: bool = True
    direct_100_drive_present: bool = False
    direct_150_drive_present: bool = False
    target_frequency_injection_present: bool = False
    behavioral_helper: bool = False
    notes: str = ""


@dataclass(frozen=True)
class NLTLExport:
    case: NLTLCase
    netlist_path: Path
    csv_path: Path


@dataclass(frozen=True)
class RunResult:
    execution_status: str
    success: bool
    reason: str
    log_path: Path | None = None


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def write_csv(path: Path, rows: List[Dict[str, object]]) -> None:
    if not rows:
        return
    keys: List[str] = []
    for row in rows:
        for key in row:
            if key not in keys:
                keys.append(key)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def spice_num(value: float) -> str:
    if value == 0.0:
        return "0"
    return f"{value:.12g}"


def safe_float(value: object, default: float = 0.0) -> float:
    try:
        result = float(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return default
    return result if math.isfinite(result) else default


def sh_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def resolve_ngspice_path(raw_path: str | None) -> str | None:
    if raw_path:
        if raw_path.startswith("wsl:"):
            tool = raw_path.split(":", 1)[1] or "ngspice"
            probe = subprocess.run(
                ["wsl", "-e", "sh", "-lc", f"command -v {sh_quote(tool)} >/dev/null 2>&1"],
                text=True,
                capture_output=True,
                timeout=30,
                check=False,
            )
            return raw_path if probe.returncode == 0 else None
        candidate = Path(raw_path)
        if candidate.exists():
            return str(candidate)
        return shutil.which(raw_path)
    return spice_base.resolve_ngspice_path(None)


def n(node_idx: int) -> str:
    return f"n{node_idx}"


def cell_values(case: NLTLCase) -> Dict[str, float]:
    dx = case.total_length_m / case.cell_count
    vp = case.phase_velocity_m_s
    z0 = case.z0_ohm
    l_cell = z0 * dx / vp
    c_cell = dx / (z0 * vp)
    c_var_eff = c_cell * case.nonlinear_fraction
    c_fixed = max(c_cell - c_var_eff, c_cell * 0.03)
    cjo = c_var_eff * (1.0 + case.bias_v / max(case.varactor_vj_v, EPS)) ** case.varactor_m
    r_series = 0.035 * case.series_loss_ohm_scale * math.sqrt(max(z0, 1.0) / 50.0) * (32.0 / case.cell_count)
    fc_hz = vp / (math.pi * dx)
    return {
        "dx_m": dx,
        "l_cell_h": l_cell,
        "c_cell_f": c_cell,
        "c_fixed_f": 0.0 if case.fixed_cap_only else c_fixed,
        "c_linear_control_f": c_cell,
        "c_var_eff_f": 0.0 if case.fixed_cap_only else c_var_eff,
        "cjo_f": 0.0 if case.fixed_cap_only else cjo,
        "r_series_ohm": r_series,
        "fc_hz": fc_hz,
        "estimated_z0_ohm": math.sqrt(max(l_cell, EPS) / max(c_cell, EPS)),
        "phase_velocity_m_s": dx / math.sqrt(max(l_cell * c_cell, EPS)),
    }


def build_cases(max_discovery_cases: int | None = None) -> List[NLTLCase]:
    cases: List[NLTLCase] = []
    idx = 1
    for cells in (12, 16, 24, 32, 48):
        for z0 in (25.0, 50.0, 75.0):
            cases.append(
                NLTLCase(
                    case_id=f"d{idx:03d}",
                    name=f"varactor_nltl_{cells}cells_{int(z0)}ohm",
                    filename=f"varactor_nltl_{cells}cells_{int(z0)}ohm.cir",
                    role="discovery",
                    cell_count=cells,
                    z0_ohm=z0,
                    notes="Source-only varactor-loaded NLTL discovery row.",
                )
            )
            idx += 1
    if max_discovery_cases is not None:
        cases = cases[:max_discovery_cases]

    best = NLTLCase(
        case_id="base",
        name="control_base",
        filename="control_base.cir",
        role="control",
        cell_count=48,
        z0_ohm=50.0,
    )
    controls = [
        replace(
            best,
            case_id="c001",
            name="linear_fixed_capacitor_line",
            filename="linear_fixed_capacitor_line.cir",
            fixed_cap_only=True,
            nonlinear_fraction=0.0,
            notes="Linear/no-nonlinearity control using fixed shunt capacitors instead of varactors.",
        ),
        replace(
            best,
            case_id="c002",
            name="weak_varactor_nonlinearity_line",
            filename="weak_varactor_nonlinearity_line.cir",
            nonlinear_fraction=0.08,
            bias_v=14.0,
            notes="Weak-nonlinearity control with small capacitance swing from high reverse bias.",
        ),
        replace(
            best,
            case_id="c003",
            name="detuned_target_phase_velocity_line",
            filename="detuned_target_phase_velocity_line.cir",
            phase_velocity_m_s=3.8e6,
            target_phase_velocity_scale=0.82,
            generated_phase_velocity_scale=0.92,
            notes="Control with band-shunt values detuned away from 150 MHz phase matching.",
        ),
        replace(
            best,
            case_id="c004",
            name="shuffled_frequency_line",
            filename="shuffled_frequency_line.cir",
            phase_velocity_m_s=6.2e6,
            notes="Shuffled velocity/frequency mapping control.",
        ),
        replace(
            best,
            case_id="c005",
            name="too_short_line",
            filename="too_short_line.cir",
            total_length_m=TOTAL_LENGTH_M * 0.20,
            notes="Too-short interaction-length control.",
        ),
        replace(
            best,
            case_id="c006",
            name="too_lossy_line",
            filename="too_lossy_line.cir",
            series_loss_ohm_scale=24.0,
            shunt_loss_ohm=15_000.0,
            notes="Too-lossy distributed line control.",
        ),
        replace(
            best,
            case_id="direct_50plus100_reference",
            name="direct_50plus100_reference",
            filename="direct_50plus100_reference.cir",
            role="ceiling_reference",
            direct_generated_amplitude_v=1.0,
            source_only_drive=False,
            direct_100_drive_present=True,
            notes="Separated direct 50+100 MHz ceiling reference; not a discovery row.",
        ),
    ]
    return cases + controls


def band_shunt_values(case: NLTLCase, vals: Dict[str, float]) -> Dict[str, float]:
    # Weak high-Q shunts nudge harmonic phase velocity without acting as a target source.
    c8 = vals["c_cell_f"] * 0.035
    c12 = vals["c_cell_f"] * 0.028
    f8 = GENERATED_HZ * case.generated_phase_velocity_scale
    f12 = TARGET_HZ * case.target_phase_velocity_scale
    l8 = 1.0 / ((2.0 * math.pi * f8) ** 2 * c8)
    l12 = 1.0 / ((2.0 * math.pi * f12) ** 2 * c12)
    r8 = case.z0_ohm * 28.0
    r12 = case.z0_ohm * 34.0
    return {"c8_f": c8, "l8_h": l8, "r8_ohm": r8, "c12_f": c12, "l12_h": l12, "r12_ohm": r12}


def netlist_for_case(case: NLTLCase, csv_path: Path) -> str:
    vals = cell_values(case)
    var = VaractorModel(
        cjo_f=max(vals["cjo_f"], 1.0e-15),
        vj_v=case.varactor_vj_v,
        m=case.varactor_m,
        rs_ohm=case.varactor_rs_ohm,
        bv_v=case.varactor_bv_v,
        ibv_a=case.varactor_ibv_a,
    )
    mid = max(1, case.cell_count // 2)
    out = case.cell_count
    lines = [
        f"* {case.name}",
        "* Varactor-loaded NLTL 4->8->12 bench design track.",
        f"* role={case.role}; source_only={case.source_only_drive}; direct_100={case.direct_100_drive_present}; direct_150=False",
        f".option method=gear maxord=2 reltol=2e-4 abstol=1e-12 vntol=1e-6 chgtol=1e-16 itl4=200",
        f".model DVAR D(Is={spice_num(var.is_a)} Rs={spice_num(var.rs_ohm)} Cjo={spice_num(var.cjo_f)} Vj={spice_num(var.vj_v)} M={spice_num(var.m)} Bv={spice_num(var.bv_v)} Ibv={spice_num(var.ibv_a)})",
        f"Vbias vb 0 DC {spice_num(case.bias_v)}",
        f"Vsrc src 0 SIN(0 {spice_num(case.source_amplitude_v)} {spice_num(SOURCE_HZ)})",
        f"Rsrc src {n(0)} {spice_num(case.z0_ohm)}",
        f"Rload {n(out)} 0 {spice_num(case.z0_ohm)}",
    ]
    if case.direct_generated_amplitude_v > 0.0:
        lines.extend(
            [
                f"Vgen gen_src 0 SIN(0 {spice_num(case.direct_generated_amplitude_v)} {spice_num(GENERATED_HZ)})",
                f"Rgen gen_src {n(0)} {spice_num(case.z0_ohm * 1.25)}",
            ]
        )
    if case.fixed_cap_only:
        lines.append(f"Cbase0 {n(0)} 0 {spice_num(vals['c_linear_control_f'])}")
    else:
        lines.append(f"Cfixed0 {n(0)} 0 {spice_num(vals['c_fixed_f'])}")
        lines.append(f"Dvar0 {n(0)} vb DVAR")
    lines.append(f"Rbleed0 {n(0)} 0 {spice_num(case.shunt_loss_ohm)}")

    shunt = band_shunt_values(case, vals)
    for i in range(1, case.cell_count + 1):
        lines.extend(
            [
                f"Rser{i} {n(i - 1)} ns{i} {spice_num(vals['r_series_ohm'])}",
                f"Lser{i} ns{i} {n(i)} {spice_num(vals['l_cell_h'])}",
            ]
        )
        if case.fixed_cap_only:
            lines.append(f"Cbase{i} {n(i)} 0 {spice_num(vals['c_linear_control_f'])}")
        else:
            lines.append(f"Cfixed{i} {n(i)} 0 {spice_num(vals['c_fixed_f'])}")
            lines.append(f"Dvar{i} {n(i)} vb DVAR")
        lines.append(f"Rbleed{i} {n(i)} 0 {spice_num(case.shunt_loss_ohm)}")
        if case.band_shunts and not case.fixed_cap_only:
            lines.extend(
                [
                    f"R8_{i} {n(i)} b8r{i} {spice_num(shunt['r8_ohm'])}",
                    f"L8_{i} b8r{i} b8l{i} {spice_num(shunt['l8_h'])}",
                    f"C8_{i} b8l{i} 0 {spice_num(shunt['c8_f'])}",
                    f"R12_{i} {n(i)} b12r{i} {spice_num(shunt['r12_ohm'])}",
                    f"L12_{i} b12r{i} b12l{i} {spice_num(shunt['l12_h'])}",
                    f"C12_{i} b12l{i} 0 {spice_num(shunt['c12_f'])}",
                ]
            )

    if case.behavioral_helper:
        lines.append("* Behavioral helper intentionally disabled in current discovery rows.")

    csv_name = csv_path.name
    lines.extend(
        [
            ".control",
            "set filetype=ascii",
            "set wr_singlescale",
            "set wr_vecnames",
            f"tran {spice_num(TSTEP_S)} {spice_num(TSTOP_S)} 0 {spice_num(TMAX_STEP_S)}",
            f"wrdata {csv_name} time v({n(0)}) v({n(mid)}) v({n(out)}) i(Vsrc) i(Vbias)",
            ".endc",
            ".end",
            "",
        ]
    )
    return "\n".join(lines)


def export_netlists(out_dir: Path, max_discovery_cases: int | None = None) -> List[NLTLExport]:
    ensure_dir(out_dir)
    exports: List[NLTLExport] = []
    for case in build_cases(max_discovery_cases=max_discovery_cases):
        netlist_path = out_dir / case.filename
        csv_path = out_dir / f"{Path(case.filename).stem}_tran.csv"
        netlist_path.write_text(netlist_for_case(case, csv_path), encoding="utf-8")
        exports.append(NLTLExport(case=case, netlist_path=netlist_path, csv_path=csv_path))
    return exports


def run_ngspice(export: NLTLExport, ngspice_path: str, timeout_s: int) -> RunResult:
    base_export = type("ExportShim", (), {"netlist_path": export.netlist_path, "csv_path": export.csv_path})()
    result = spice_base.run_ngspice(base_export, ngspice_path, timeout_s)
    return RunResult(result.execution_status, result.success, result.reason, result.log_path)


def try_float(token: str) -> float | None:
    try:
        return float(token)
    except ValueError:
        return None


def read_transient(path: Path) -> Dict[str, np.ndarray]:
    # Ngspice wrdata sometimes repeats the scale column when headers are enabled.
    lines = [line.strip() for line in path.read_text(encoding="utf-8", errors="ignore").splitlines() if line.strip()]
    if not lines:
        raise ValueError(f"empty transient CSV {path}")
    first = lines[0].replace(",", " ").split()
    has_header = any(try_float(tok) is None for tok in first)
    data_lines = lines[1:] if has_header else lines
    rows: List[List[float]] = []
    for line in data_lines:
        vals = [try_float(tok) for tok in line.replace(",", " ").split()]
        numeric = [float(v) for v in vals if v is not None]
        if numeric:
            rows.append(numeric)
    if not rows:
        raise ValueError(f"no numeric rows in {path}")
    width = min(len(row) for row in rows)
    arr = np.asarray([row[:width] for row in rows], dtype=float)
    if width >= 11 and np.allclose(arr[:, 0], arr[:, 2]):
        return {
            "time": arr[:, 0],
            "v_in": arr[:, 3],
            "v_mid": arr[:, 5],
            "v_out": arr[:, 7],
            "i_src": arr[:, 9],
            "i_bias": arr[:, 11] if width > 11 else arr[:, 9] * 0.0,
        }
    if width >= 6:
        return {
            "time": arr[:, 0],
            "v_in": arr[:, 1],
            "v_mid": arr[:, 2],
            "v_out": arr[:, 3],
            "i_src": arr[:, 4],
            "i_bias": arr[:, 5],
        }
    raise ValueError(f"expected transient table with time/vin/vmid/vout/isrc/ibias, got {width} columns")


def uniform_resample(data: Dict[str, np.ndarray], max_points: int = 12000) -> Dict[str, np.ndarray]:
    t = np.asarray(data["time"], dtype=float)
    finite = np.isfinite(t)
    for key in ("v_in", "v_mid", "v_out", "i_src", "i_bias"):
        finite &= np.isfinite(np.asarray(data[key], dtype=float))
    order = np.argsort(t[finite])
    t_sorted = t[finite][order]
    keep = np.concatenate(([True], np.diff(t_sorted) > 0.0))
    t_sorted = t_sorted[keep]
    if len(t_sorted) < 16:
        raise ValueError("not enough unique transient samples")
    n_points = min(max_points, len(t_sorted))
    target_t = np.linspace(t_sorted[0], t_sorted[-1], n_points)
    result = {"time": target_t}
    for key in ("v_in", "v_mid", "v_out", "i_src", "i_bias"):
        y = np.asarray(data[key], dtype=float)[finite][order][keep]
        result[key] = np.interp(target_t, t_sorted, y)
    return result


def complex_projection(signal: np.ndarray, t: np.ndarray, freq_hz: float) -> complex:
    return 2.0 * np.mean(signal * np.exp(-1j * 2.0 * math.pi * freq_hz * t))


def sliding_projection(signal: np.ndarray, t: np.ndarray, freq_hz: float, cycles: int = 8) -> Tuple[np.ndarray, np.ndarray]:
    dt = float(np.median(np.diff(t)))
    window = max(16, int(round(cycles / (freq_hz * max(dt, EPS)))))
    step = max(4, window // 4)
    amps: List[float] = []
    phases: List[float] = []
    for start in range(0, len(signal) - window, step):
        stop = start + window
        z = complex_projection(signal[start:stop], t[start:stop], freq_hz)
        amps.append(abs(z))
        phases.append(float(np.angle(z)))
    return np.asarray(amps), np.asarray(phases)


def fft_peak(signal: np.ndarray, t: np.ndarray, lo_hz: float, hi_hz: float) -> Tuple[float, float]:
    dt = float(np.median(np.diff(t)))
    centered = signal - np.mean(signal)
    window = np.hanning(len(centered))
    spec = np.fft.rfft(centered * window)
    freqs = np.fft.rfftfreq(len(centered), dt)
    power = np.abs(spec) ** 2
    mask = (freqs >= lo_hz) & (freqs <= hi_hz)
    if not np.any(mask):
        return 0.0, 0.0
    idxs = np.nonzero(mask)[0]
    peak_idx = idxs[int(np.argmax(power[mask]))]
    return float(freqs[peak_idx]), float(power[peak_idx])


def band_power(signal: np.ndarray, t: np.ndarray, center_hz: float, half_width_hz: float) -> float:
    dt = float(np.median(np.diff(t)))
    centered = signal - np.mean(signal)
    spec = np.fft.rfft(centered * np.hanning(len(centered)))
    freqs = np.fft.rfftfreq(len(centered), dt)
    power = np.abs(spec) ** 2
    mask = (freqs >= center_hz - half_width_hz) & (freqs <= center_hz + half_width_hz)
    return float(np.sum(power[mask]))


def measure_case(export: NLTLExport, data: Dict[str, np.ndarray], reference_power: float | None) -> Dict[str, object]:
    case = export.case
    vals = cell_values(case)
    d = uniform_resample(data)
    t = d["time"]
    start = int(0.25 * len(t))
    t2 = t[start:]
    vout = d["v_out"][start:]
    vin = d["v_in"][start:]
    i_src = d["i_src"][start:]
    i_bias = d["i_bias"][start:]

    source_peak, source_power = fft_peak(vout, t2, SOURCE_HZ * 0.85, SOURCE_HZ * 1.15)
    gen_peak, gen_power = fft_peak(vout, t2, GENERATED_HZ * 0.85, GENERATED_HZ * 1.15)
    target_peak, target_power = fft_peak(vout, t2, TARGET_HZ * 0.85, TARGET_HZ * 1.15)
    target_band = band_power(vout, t2, TARGET_HZ, 8.0e6)
    broad_power = band_power(vout, t2, 10.0e6, 190.0e6)
    purity = target_band / max(broad_power, EPS)

    gen_amp, gen_phase = sliding_projection(vout, t2, GENERATED_HZ, cycles=8)
    target_amp, target_phase = sliding_projection(vout, t2, TARGET_HZ, cycles=8)
    source_amp, source_phase = sliding_projection(vout, t2, SOURCE_HZ, cycles=8)
    n_gen = min(len(gen_phase), len(source_phase))
    n_target = min(len(target_phase), len(source_phase))
    phase_lock_generated = (
        float(abs(np.mean(np.exp(1j * (gen_phase[:n_gen] - 2.0 * source_phase[:n_gen])))))
        if n_gen
        else 0.0
    )
    phase_lock_target = (
        float(abs(np.mean(np.exp(1j * (target_phase[:n_target] - 3.0 * source_phase[:n_target])))))
        if n_target
        else 0.0
    )
    generated_cv = float(np.std(gen_amp) / max(np.mean(gen_amp), EPS)) if len(gen_amp) else 0.0
    target_cv = float(np.std(target_amp) / max(np.mean(target_amp), EPS)) if len(target_amp) else 0.0
    if len(target_phase) > 2:
        phase_jumps = np.abs(np.diff(np.unwrap(target_phase)))
        max_phase_jump = float(np.max(phase_jumps))
        near_slips = float(np.sum(phase_jumps > 1.0))
    else:
        max_phase_jump = 0.0
        near_slips = 0.0

    first = max(1, len(target_amp) // 5)
    last = max(1, len(target_amp) // 5)
    target_growth = float(np.mean(target_amp[-last:]) / max(np.mean(target_amp[:first]), EPS)) if len(target_amp) else 0.0
    coherent_power = float(abs(complex_projection(vout, t2, TARGET_HZ)) ** 2)
    bridge_ratio = coherent_power / max(reference_power or coherent_power, EPS) if reference_power is not None else 0.0

    peak_line_voltage = float(max(np.max(np.abs(d["v_in"])), np.max(np.abs(d["v_mid"])), np.max(np.abs(d["v_out"]))))
    peak_bias_current = float(np.max(np.abs(d["i_bias"])))
    peak_varactor_current = peak_bias_current / max(case.cell_count + 1, 1)
    peak_src_current = float(np.max(np.abs(d["i_src"])))
    reverse_bias_margin = case.bias_v - peak_line_voltage
    avg_source_power = float(abs(np.mean((case.source_amplitude_v * np.sin(2.0 * math.pi * SOURCE_HZ * t2)) * i_src)))
    dissipation_estimate = avg_source_power * (t2[-1] - t2[0])

    stress_voltage = peak_line_voltage / max(case.bias_v * 0.85, EPS)
    stress_current = peak_varactor_current / 0.020
    stress_breakdown = max(0.0, (case.bias_v + peak_line_voltage) / max(case.varactor_bv_v, EPS))
    component_stress_score = float(max(stress_voltage, stress_current, stress_breakdown))
    if component_stress_score < 0.75 and reverse_bias_margin > 0.25:
        stress_class = "plausible"
    elif component_stress_score < 1.35 and reverse_bias_margin > -0.5:
        stress_class = "aggressive-but-testable"
    else:
        stress_class = "unrealistic"

    behavioral_dependency = 0.08 + (0.12 if case.band_shunts else 0.0) + (0.12 if case.behavioral_helper else 0.0)
    if case.fixed_cap_only:
        behavioral_dependency = 0.02
    controls_clean_placeholder = True
    bench_feasibility = float(
        0.30 * min(1.0, vals["fc_hz"] / (TARGET_HZ * 1.2))
        + 0.20 * max(0.0, 1.0 - min(1.0, component_stress_score / 1.5))
        + 0.20 * min(1.0, target_growth / 2.0)
        + 0.15 * min(1.0, purity)
        + 0.15 * max(0.0, 1.0 - behavioral_dependency / TL_BEHAVIORAL_BASELINE)
    )

    control_leakage_score = min(
        1.0,
        max(target_growth - 1.0, 0.0) / 2.0
        + max(purity - 0.20, 0.0)
        + (max(bridge_ratio - 1.5, 0.0) / 2.0 if purity > 0.20 else 0.0),
    )

    promotion = "not_promoted"
    if case.role == "discovery":
        if (
            phase_lock_target > 0.90
            and bridge_ratio > 1.5
            and purity > 0.80
            and target_growth > 1.0
            and generated_cv < 0.25
            and max_phase_jump < 1.0
            and stress_class in {"plausible", "aggressive-but-testable"}
            and behavioral_dependency <= TL_BEHAVIORAL_BASELINE
        ):
            promotion = "spice_varactor_nltl_candidate"
        elif phase_lock_target > 0.50 and bridge_ratio > 1.0 and purity > 0.80:
            promotion = "near_miss"
    elif case.role == "control":
        promotion = "control_dead" if control_leakage_score < 0.15 else "control_leakage"
    else:
        promotion = "ceiling_reference_not_discovery"

    return {
        "source_fft_peak_hz": source_peak,
        "generated_fft_peak_hz": gen_peak,
        "target_fft_peak_hz": target_peak,
        "source_fft_power": source_power,
        "generated_fft_power": gen_power,
        "target_fft_power": target_power,
        "target_band_coherent_growth": target_growth,
        "target_coherent_power": coherent_power,
        "phase_lock_target": phase_lock_target,
        "phase_lock_generated": phase_lock_generated,
        "bridge_ratio_vs_direct_reference": bridge_ratio,
        "spectral_purity_150mhz": purity,
        "generated_envelope_cv": generated_cv,
        "target_envelope_cv": target_cv,
        "max_phase_jump": max_phase_jump,
        "near_slip_count": near_slips,
        "control_leakage_score": 0.0 if case.role != "control" else control_leakage_score,
        "estimated_line_impedance_ohm": vals["estimated_z0_ohm"],
        "phase_velocity_m_s": vals["phase_velocity_m_s"],
        "cell_length_m": vals["dx_m"],
        "per_cell_inductance_h": vals["l_cell_h"],
        "per_cell_total_capacitance_f": vals["c_cell_f"],
        "per_cell_fixed_capacitance_f": vals["c_fixed_f"],
        "varactor_cjo_f": vals["cjo_f"],
        "ladder_cutoff_hz": vals["fc_hz"],
        "varactor_peak_voltage_v": peak_line_voltage,
        "varactor_peak_current_a": peak_varactor_current,
        "source_peak_current_a": peak_src_current,
        "reverse_bias_margin_v": reverse_bias_margin,
        "dissipation_estimate_j": dissipation_estimate,
        "component_stress_score": component_stress_score,
        "component_stress_class": stress_class,
        "behavioral_dependency_score": behavioral_dependency,
        "bench_feasibility_score": bench_feasibility,
        "promotion_category": promotion,
    }


def summarize_export(export: NLTLExport, run_requested: bool, ngspice_available: bool,
                     ngspice_path: str | None, result: RunResult,
                     metrics: Dict[str, object] | None) -> Dict[str, object]:
    case = export.case
    vals = cell_values(case)
    row: Dict[str, object] = {
        "row_type": "spice_varactor_nltl",
        "case_id": case.case_id,
        "name": case.name,
        "role": case.role,
        "netlist_file": export.netlist_path.name,
        "csv_file": export.csv_path.name if result.success else "",
        "execution_status": result.execution_status,
        "convergence_failure_reason": "" if result.success else result.reason,
        "run_requested": str(run_requested),
        "ngspice_available": str(ngspice_available),
        "ngspice_path": ngspice_path or "",
        "source_only_drive": str(case.source_only_drive),
        "direct_100mhz_drive_present": str(case.direct_100_drive_present),
        "direct_150mhz_drive_present": str(case.direct_150_drive_present),
        "target_frequency_injection_present": str(case.target_frequency_injection_present),
        "cell_count": case.cell_count,
        "total_length_m": case.total_length_m,
        "cell_length_m": vals["dx_m"],
        "z0_target_ohm": case.z0_ohm,
        "source_frequency_hz": SOURCE_HZ,
        "generated_frequency_hz": GENERATED_HZ,
        "target_frequency_hz": TARGET_HZ,
        "source_amplitude_v": case.source_amplitude_v,
        "direct_generated_amplitude_v": case.direct_generated_amplitude_v,
        "bias_v": case.bias_v,
        "nonlinear_fraction": case.nonlinear_fraction,
        "varactor_vj_v": case.varactor_vj_v,
        "varactor_m": case.varactor_m,
        "varactor_rs_ohm": case.varactor_rs_ohm,
        "varactor_bv_v": case.varactor_bv_v,
        "varactor_ibv_a": case.varactor_ibv_a,
        "fixed_cap_only": str(case.fixed_cap_only),
        "band_shunts": str(case.band_shunts),
        "behavioral_helper_present": str(case.behavioral_helper),
        "notes": case.notes,
    }
    if metrics:
        row.update(metrics)
    return row


def aggregate_summary(rows: List[Dict[str, object]], run_requested: bool, ngspice_available: bool) -> Dict[str, object]:
    data_rows = [r for r in rows if r.get("row_type") == "spice_varactor_nltl"]
    discovery = [r for r in data_rows if r.get("role") == "discovery"]
    controls = [r for r in data_rows if r.get("role") == "control"]
    ran = [r for r in data_rows if r.get("execution_status") == "ran_successfully"]
    candidates = [r for r in discovery if r.get("promotion_category") == "spice_varactor_nltl_candidate"]
    near = [r for r in discovery if r.get("promotion_category") == "near_miss"]
    successful_discovery = [r for r in discovery if r.get("execution_status") == "ran_successfully"]
    best = max(
        successful_discovery,
        key=lambda r: (
            safe_float(r.get("bench_feasibility_score")),
            safe_float(r.get("bridge_ratio_vs_direct_reference")),
            safe_float(r.get("phase_lock_target")),
        ),
        default={},
    )
    best_bridge = max(successful_discovery, key=lambda r: safe_float(r.get("bridge_ratio_vs_direct_reference")), default={})
    control_leak = max((safe_float(r.get("control_leakage_score")) for r in controls), default=0.0)
    controls_dead = all(str(r.get("promotion_category")) == "control_dead" for r in controls if r.get("execution_status") == "ran_successfully")
    statuses = ";".join(sorted(set(str(r.get("execution_status")) for r in data_rows)))
    best_cell_count = best.get("cell_count", "")
    best_z0 = best.get("z0_target_ohm", "")
    recommended = "component selection/BOM and PCB layout model" if candidates else "component selection/BOM plus stronger varactor sweep before PCB layout"
    return {
        "row_type": "aggregate",
        "valid_spice_netlists_generated": str(all((OUT_DIR / str(r.get("netlist_file"))).exists() for r in data_rows)),
        "run_requested": str(run_requested),
        "ngspice_available": str(ngspice_available),
        "execution_statuses": statuses,
        "rows_total": len(data_rows),
        "discovery_rows": len(discovery),
        "control_rows": len(controls),
        "ran_successfully_count": len(ran),
        "candidate_count": len(candidates),
        "near_miss_count": len(near),
        "best_case": best.get("case_id", ""),
        "best_name": best.get("name", ""),
        "best_cell_count": best_cell_count,
        "best_impedance_ohm": best_z0,
        "best_phase_lock_target": best.get("phase_lock_target", ""),
        "best_bridge_ratio": best.get("bridge_ratio_vs_direct_reference", ""),
        "best_purity": best.get("spectral_purity_150mhz", ""),
        "best_target_growth": best.get("target_band_coherent_growth", ""),
        "best_generated_cv": best.get("generated_envelope_cv", ""),
        "best_max_phase_jump": best.get("max_phase_jump", ""),
        "best_component_stress_score": best.get("component_stress_score", ""),
        "best_component_stress_class": best.get("component_stress_class", ""),
        "best_behavioral_dependency_score": best.get("behavioral_dependency_score", ""),
        "best_bench_feasibility_score": best.get("bench_feasibility_score", ""),
        "best_bridge_case": best_bridge.get("case_id", ""),
        "best_bridge_ratio_case_value": best_bridge.get("bridge_ratio_vs_direct_reference", ""),
        "controls_dead": str(controls_dead) if ran else "not_run",
        "max_control_leakage_score": control_leak,
        "behavioral_dependency_lower_than_tl_baseline": str(safe_float(best.get("behavioral_dependency_score"), 1.0) <= TL_BEHAVIORAL_BASELINE),
        "design_bench_buildable": str(bool(candidates) or bool(near)),
        "recommended_next_step": recommended,
    }


def timeseries_rows(export: NLTLExport, data: Dict[str, np.ndarray], stride: int = 20) -> List[Dict[str, object]]:
    d = uniform_resample(data, max_points=6000)
    rows: List[Dict[str, object]] = []
    for idx in range(0, len(d["time"]), stride):
        rows.append(
            {
                "row_type": "spice_varactor_nltl_timeseries",
                "case_id": export.case.case_id,
                "name": export.case.name,
                "time_s": float(d["time"][idx]),
                "v_in": float(d["v_in"][idx]),
                "v_mid": float(d["v_mid"][idx]),
                "v_out": float(d["v_out"][idx]),
                "i_src": float(d["i_src"][idx]),
                "i_bias": float(d["i_bias"][idx]),
            }
        )
    return rows


def write_report(out_dir: Path, rows: List[Dict[str, object]], aggregate: Dict[str, object]) -> None:
    data_rows = [r for r in rows if r.get("row_type") == "spice_varactor_nltl"]
    best_name = aggregate.get("best_name") or "none"
    lines = [
        "# SPICE 4->8->12 Varactor NLTL Design",
        "",
        "Bench-oriented varactor-loaded nonlinear transmission-line design at 50/100/150 MHz.",
        "",
        "## Direct Answers",
        "",
        (
            "1. Can a realistic varactor-loaded NLTL preserve the bridge? "
            f"candidates={aggregate.get('candidate_count')}; near_misses={aggregate.get('near_miss_count')}; "
            f"best={best_name}."
        ),
        (
            "2. Best cell count and impedance: "
            f"{aggregate.get('best_cell_count')} cells at {aggregate.get('best_impedance_ohm')} ohm."
        ),
        (
            "3. Stress plausibility: "
            f"{aggregate.get('best_component_stress_class')} with stress score {aggregate.get('best_component_stress_score')}."
        ),
        (
            "4. Controls stay dead? "
            f"{aggregate.get('controls_dead')}; max leakage={aggregate.get('max_control_leakage_score')}."
        ),
        (
            "5. Behavioral dependency: "
            f"best={aggregate.get('best_behavioral_dependency_score')}; "
            f"lower_than_0.36={aggregate.get('behavioral_dependency_lower_than_tl_baseline')}."
        ),
        (
            "6. Bench-buildable? "
            f"{aggregate.get('design_bench_buildable')} with best feasibility {aggregate.get('best_bench_feasibility_score')}."
        ),
        f"7. Next step: {aggregate.get('recommended_next_step')}.",
        "",
        "## Rows",
        "",
    ]
    for row in data_rows:
        lines.append(
            "- {case_id} {name}: role={role}, status={status}, category={cat}, cells={cells}, "
            "z0={z0}, lock={lock}, bridge={bridge}, purity={purity}, stress={stress}, behavioral={beh}.".format(
                case_id=row.get("case_id"),
                name=row.get("name"),
                role=row.get("role"),
                status=row.get("execution_status"),
                cat=row.get("promotion_category", ""),
                cells=row.get("cell_count"),
                z0=row.get("z0_target_ohm"),
                lock=row.get("phase_lock_target", ""),
                bridge=row.get("bridge_ratio_vs_direct_reference", ""),
                purity=row.get("spectral_purity_150mhz", ""),
                stress=row.get("component_stress_class", ""),
                beh=row.get("behavioral_dependency_score", ""),
            )
        )
    lines.extend(
        [
            "",
            "## Circuit Notes",
            "",
            "- Discovery rows drive only the 50 MHz source band.",
            "- Generated 100 MHz and target 150 MHz content arise from reverse-biased varactor diode capacitance.",
            "- The direct 50+100 MHz reference is separated and is not a discovery row.",
            "- Band-selective shunts are passive phase-velocity controls, not target-frequency sources.",
        ]
    )
    (out_dir / "README_SPICE_412_VARACTOR_NLTL_DESIGN.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export and optionally run varactor-loaded NLTL SPICE designs.")
    parser.add_argument("--out", default=str(OUT_DIR), help="Output directory.")
    parser.add_argument("--run", action="store_true", help="Run ngspice after exporting netlists.")
    parser.add_argument("--ngspice-path", default="", help="Path to ngspice or wsl:ngspice.")
    parser.add_argument("--timeout", type=int, default=180, help="Timeout per netlist in seconds.")
    parser.add_argument("--max-discovery-cases", type=int, default=0, help="Limit discovery rows for quick debugging.")
    args = parser.parse_args()

    out_dir = ensure_dir(Path(args.out))
    max_discovery = args.max_discovery_cases if args.max_discovery_cases > 0 else None
    exports = export_netlists(out_dir, max_discovery_cases=max_discovery)
    ngspice_path = resolve_ngspice_path(args.ngspice_path or None)
    ngspice_available = ngspice_path is not None

    run_results: Dict[str, RunResult] = {}
    parsed: Dict[str, Dict[str, np.ndarray]] = {}
    if args.run and not ngspice_available:
        for export in exports:
            run_results[export.case.case_id] = RunResult("skipped_no_ngspice", False, "ngspice not found")
    elif args.run and ngspice_path:
        for export in exports:
            result = run_ngspice(export, ngspice_path, args.timeout)
            if result.success:
                try:
                    parsed[export.case.case_id] = read_transient(export.csv_path)
                except Exception as exc:
                    result = RunResult("parser_failed", False, f"{type(exc).__name__}: {exc}", result.log_path)
            run_results[export.case.case_id] = result
    else:
        for export in exports:
            run_results[export.case.case_id] = RunResult("exported", False, "export only; use --run")

    reference_power: float | None = None
    reference = next((export for export in exports if export.case.role == "ceiling_reference"), None)
    if reference and reference.case.case_id in parsed:
        ref_metrics = measure_case(reference, parsed[reference.case.case_id], None)
        reference_power = safe_float(ref_metrics.get("target_coherent_power"))

    summary_rows: List[Dict[str, object]] = []
    ts_rows: List[Dict[str, object]] = []
    for export in exports:
        result = run_results[export.case.case_id]
        metrics: Dict[str, object] | None = None
        if result.success and export.case.case_id in parsed:
            metrics = measure_case(export, parsed[export.case.case_id], reference_power)
            if export.case.role in {"discovery", "ceiling_reference"}:
                ts_rows.extend(timeseries_rows(export, parsed[export.case.case_id]))
        summary_rows.append(summarize_export(export, args.run, ngspice_available, ngspice_path, result, metrics))

    aggregate = aggregate_summary(summary_rows, args.run, ngspice_available)
    all_rows = [aggregate] + summary_rows
    write_csv(out_dir / "spice_412_varactor_nltl_summary.csv", all_rows)
    if ts_rows:
        write_csv(out_dir / "spice_412_varactor_nltl_timeseries.csv", ts_rows)
    timeseries_path = out_dir / "spice_412_varactor_nltl_timeseries.csv"
    if not ts_rows and timeseries_path.exists():
        timeseries_path.unlink()
    (out_dir / "spice_412_varactor_nltl_summary.json").write_text(
        json.dumps(
            {
                "aggregate": aggregate,
                "rows": all_rows,
                "netlists": [
                    {
                        **asdict(export.case),
                        "netlist_path": str(export.netlist_path),
                        "csv_path": str(export.csv_path),
                    }
                    for export in exports
                ],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    write_report(out_dir, all_rows, aggregate)
    print(
        "spice_412_varactor_nltl_design: run={run} ngspice={ng} statuses={st} best={best} candidates={cand} near={near}".format(
            run=args.run,
            ng=ngspice_available,
            st=aggregate["execution_statuses"],
            best=aggregate["best_name"],
            cand=aggregate["candidate_count"],
            near=aggregate["near_miss_count"],
        )
    )


if __name__ == "__main__":
    main()
